controller_manager:
  ros__parameters:
    update_rate: 1000 #  Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot_joint_controller:
      type: forward_command_controller/ForwardCommandController  
robot_joint_controller:
  ros__parameters:
    joints:
      - front_left_leg
      - front_left_shoulder
      - front_left_foot
      - front_right_leg
      - front_right_shoulder
      - front_right_foot
      - rear_left_leg
      - rear_left_shoulder
      - rear_left_foot
      - rear_right_leg
      - rear_right_shoulder
      - rear_right_foot
    interface_name: position
    command_interfaces:
      - position 
    state_interfaces:
      - position
      - velocity